version: '2'
services:
  base:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile

  production:
    extends: base

  development:
    extends: base
    build:
      context: ./
      dockerfile: dockerfiles/development.Dockerfile
    network_mode: "host"
    working_dir: /home
    volumes:
      - ./:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      DISPLAY: $DISPLAY
    environment:
      PYTHONPATH: /home

  test:
    extends: base
    build:
      context: ./
      dockerfile: dockerfiles/test.Dockerfile
    # command: python -m pytest --cov=./dnn tests/dnn_tests
    command: tox    

  build-docs:
    extends: base
    build:
      context: ./
      dockerfile: dockerfiles/development.Dockerfile
    working_dir: /home/docs/source
    command: make html
    volumes:
      - ./:/home
