[build]
  # base    = ""
  publish = "docs/_build/html"
  command = "source $HOME/python3.6/bin/activate && pip install -r develop.requirements.txt && pip install -e . && cd docs/source && make html"
